version: "3"

volumes:
  lldap_data:
    driver: local

services:
  lldap:
    image: nitnelave/lldap:stable
    ports:
      # For LDAP
      # - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      - "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
      - "./ldap_certs:/certs"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      # - TZ=####/####
      - LLDAP_JWT_SECRET=u7PaTT5LgtMC6fvh9nkEpOh7Jl8rLcsw
      - LLDAP_LDAP_USER_PASS=admin123
      - LLDAP_LDAP_BASE_DN=dc=omaralkersh,dc=com
      # If using LDAPS, set enabled true and configure cert and key path
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/certs/ldap.crt
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/certs/ldap.key
